"use client";
import { useEffect,useState } from "react";
import { activity,addComment,comments,getRequest,members,firstResponse,updateRequest,Activity,Comment,Membership,RequestItem } from "../../../../lib/api";
import { getAccessToken } from "../../../../lib/session";
export default function RequestDetail({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(""),[org,setOrg]=useState(""),[token,setToken]=useState(""),[item,setItem]=useState<RequestItem|null>(null),[events,setEvents]=useState<Activity[]>([]),[notes,setNotes]=useState<Comment[]>([]),[team,setTeam]=useState<Membership[]>([]),[body,setBody]=useState(""),[error,setError]=useState("");
 useEffect(()=>{params.then(p=>setId(p.id));setOrg(new URLSearchParams(location.search).get("org")??"");const t=getAccessToken();if(!t)location.href="/login";else setToken(t)},[params]);
 async function reload(){if(!token||!org||!id)return;try{const [r,a,c,m]=await Promise.all([getRequest(token,org,id),activity(token,org,id),comments(token,org,id),members(token,org)]);setItem(r);setEvents(a);setNotes(c);setTeam(m)}catch(e){setError(e instanceof Error?e.message:"Unable to load request.")}}
 useEffect(()=>{reload()},[token,org,id]);
 async function patch(data:object){if(!token)return;try{await updateRequest(token,org,id,data);await reload()}catch(e){setError(e instanceof Error?e.message:"Update failed.")}}
 async function comment(){if(!body.trim())return;try{await addComment(token,org,id,body);setBody("");await reload()}catch(e){setError(e instanceof Error?e.message:"Comment failed.")}}
 if(!item)return <main className="dashboard-shell"><p className="muted">Loading request...</p>{error&&<p className="error">{error}</p>}</main>;
 return <main className="dashboard-shell"><a href={`/dashboard?org=${org}`} className="back">← Back to inbox</a><header className="detail-header"><div><p className="eyebrow">Request detail</p><h1>{item.title}</h1><p className="muted">{item.description||"No description"}</p></div><span className={`badge ${item.sla_state}`}>{item.sla_state.replace("_"," ")}</span></header>
 <div className="detail-grid"><section className="dashboard-card"><h2>Request controls</h2><label>Status<select value={item.status} onChange={e=>patch({status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label><label>Priority<select value={item.priority} onChange={e=>patch({priority:e.target.value})}><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></label><label>Assignee<select value={item.assignee_id??""} onChange={e=>patch({assignee_id:e.target.value||null})}><option value="">Unassigned</option>{team.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name}</option>)}</select></label><div className="sla-box"><strong>SLA</strong><p>First response: {item.first_response_due_at?new Date(item.first_response_due_at).toLocaleString():"—"}</p><p>Resolution: {item.resolution_due_at?new Date(item.resolution_due_at).toLocaleString():"—"}</p><button className="secondary" onClick={()=>firstResponse(token,org,id).then(reload)}>Mark first response</button></div></section>
 <section className="dashboard-card"><h2>Comments</h2><div className="comment-list">{notes.map(c=><article className="comment" key={c.id}><strong>{team.find(m=>m.user_id===c.author_id)?.full_name??"Team member"}</strong><small>{new Date(c.created_at).toLocaleString()}</small><p>{c.body}</p></article>)}</div><textarea placeholder="Add a comment..." value={body} onChange={e=>setBody(e.target.value)}/><button onClick={comment}>Add comment</button></section>
 <section className="dashboard-card"><h2>Activity</h2><div className="timeline">{events.map(e=><article className="timeline-item" key={e.id}><small>{new Date(e.created_at).toLocaleString()}</small><p>{e.kind==="comment"?e.body:e.event_type?.replaceAll("_"," ")}</p></article>)}</div></section></div></main>;
}