"use client";
import { useEffect,useMemo,useState } from "react";
import { createOrganization,createRequest,organizations,policies,requests,analytics,notifications,Organization,RequestItem,SLAPolicy,Analytics,Notification } from "../../lib/api";
import { getAccessToken } from "../../lib/session";
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
export default function Dashboard(){
 const [token,setToken]=useState<string|null>(null),[orgs,setOrgs]=useState<Organization[]>([]),[orgId,setOrgId]=useState(""),[items,setItems]=useState<RequestItem[]>([]),[sla,setSla]=useState<SLAPolicy[]>([]);
 const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[priority,setPriority]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const [newOrg,setNewOrg]=useState(false),[orgName,setOrgName]=useState(""),[orgSlug,setOrgSlug]=useState("");
 const [newReq,setNewReq]=useState(false),[metrics,setMetrics]=useState<Analytics|null>(null),[alerts,setAlerts]=useState<Notification[]>([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[reqPriority,setReqPriority]=useState("normal"),[policyId,setPolicyId]=useState("");
 useEffect(()=>{const t=getAccessToken();if(!t){location.href="/login";return}setToken(t);organizations(t).then(o=>{setOrgs(o);if(o[0])setOrgId(o[0].id)}).catch(()=>location.href="/login").finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!token||!orgId)return;Promise.all([requests(token,orgId,{status,priority}),policies(token,orgId),analytics(token,orgId),notifications(token,orgId)]).then(([r,p,a,n])=>{setItems(r);setSla(p);setMetrics(a);setAlerts(n);if(!policyId&&p[0])setPolicyId(p[0].id)}).catch(e=>setError(e.message))},[token,orgId,status,priority]);
 const visible=useMemo(()=>items.filter(r=>r.title.toLowerCase().includes(search.toLowerCase())||r.description.toLowerCase().includes(search.toLowerCase())),[items,search]);
 async function createOrg(){if(!token)return;try{const o=await createOrganization(token,{name:orgName,slug:orgSlug});setOrgs([...orgs,o]);setOrgId(o.id);setNewOrg(false);setOrgName("");setOrgSlug("")}catch(e){setError(e instanceof Error?e.message:"Unable to create workspace.")}}
 async function createReq(){if(!token||!orgId)return;try{await createRequest(token,orgId,{title,description,priority:reqPriority,sla_policy_id:policyId});setNewReq(false);setTitle("");setDescription("");setItems(await requests(token,orgId,{status,priority}))}catch(e){setError(e instanceof Error?e.message:"Unable to create request.")}}
 if(loading)return <main className="dashboard-shell"><p className="muted">Loading workspace...</p></main>;
 return <main className="dashboard-shell">
  <header className="topbar"><div><p className="eyebrow">SLADeck workspace</p><h1>Request inbox</h1></div><div className="actions"><button className="secondary" onClick={()=>setNewOrg(true)}>New workspace</button><button className="secondary" onClick={()=>{localStorage.clear();location.href="/login"}}>Sign out</button></div></header>
  <section className="stats">{metrics&&<><Stat label="Open requests" value={metrics.open_requests}/><Stat label="Healthy" value={metrics.healthy_requests}/><Stat label="Warning" value={metrics.warning_requests}/><Stat label="Breached" value={metrics.breached_requests}/><Stat label="Breach rate" value={`${metrics.breach_rate_pct}%`}/></>}</section>
  <section className="toolbar"><select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><input placeholder="Search requests..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select><button onClick={()=>setNewReq(true)}>+ New request</button></section>
  {error&&<p className="error">{error}</p>}{alerts.length>0&&<section className="dashboard-card alert-card"><h2>Notification center</h2>{alerts.slice(0,5).map(a=><a key={a.id} href={`/dashboard/requests/${a.request_id}?org=${orgId}`} className="alert"><strong>{a.title}</strong><span>{a.message}</span><small>{new Date(a.created_at).toLocaleString()}</small></a>)}</section>}
  {!orgs.length?<section className="empty"><h2>Create your first workspace</h2><p className="muted">Requests belong to an organization, so start by creating one.</p><button onClick={()=>setNewOrg(true)}>Create workspace</button></section>:<section className="request-table"><div className="table-head"><span>Request</span><span>Priority</span><span>Status</span><span>SLA</span></div>{visible.map(r=><a className="request-row" key={r.id} href={`/dashboard/requests/${r.id}?org=${orgId}`}><span><strong>{r.title}</strong><small>{r.description||"No description"}</small></span><span className={`badge ${r.priority}`}>{r.priority}</span><span>{r.status.replace("_"," ")}</span><span className={`badge ${r.sla_state}`}>{r.sla_state.replace("_"," ")}</span></a>)}{!visible.length&&<div className="empty"><p>No requests match these filters.</p></div>}</section>}
  {newOrg&&<div className="modal"><div className="modal-card"><h2>New workspace</h2><input placeholder="Workspace name" value={orgName} onChange={e=>setOrgName(e.target.value)}/><input placeholder="slug e.g. acme-support" value={orgSlug} onChange={e=>setOrgSlug(e.target.value)}/><div className="actions"><button className="secondary" onClick={()=>setNewOrg(false)}>Cancel</button><button onClick={createOrg}>Create</button></div></div></div>}
  {newReq&&<div className="modal"><div className="modal-card"><h2>New request</h2><input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><select value={reqPriority} onChange={e=>setReqPriority(e.target.value)}><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select><select value={policyId} onChange={e=>setPolicyId(e.target.value)}>{sla.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="actions"><button className="secondary" onClick={()=>setNewReq(false)}>Cancel</button><button onClick={createReq} disabled={!policyId}>Create request</button></div></div></div>}
 </main>;
}